### PR TITLE
Add monthly downloads badge to README (ESPTOOL-876)

### PR DESCRIPTION
**Pull request by Aman-Clement**
Added a monthly downloads badge by pip Trends to the README.
View more at - https://piptrends.com/widgets/esptool

### CODE REVIEW

**Comment by radimkarnis** [comment]
Hello @Aman-Clement,
thank you for the contribution, it is always appreciated!

In this case, we don't really care about communicating how many monthly downloads esptool has. Also, this adds a dependency on an external service (piptrends.com).

I am sorry, but for this reason and to keep things simple and tidy, we would rather not accept this PR.

**Comment by Aman-Clement** [comment]
Hey @radimkarnis 
Thanks for the review! I understand the desire to keep things simple, thank you for your time. If there's any future interest in exploring download count features, feel free to reach out.

**Comment by radimkarnis** [comment]
@Aman-Clement thanks for understanding!

> If there's any future interest in exploring download count features, feel free to reach out.

Will keep you in mind 😊

**Comment by ixmatus** [comment]
It not only adds a dependency to an external service but it adds it to one that is not an officially trusted service of pypi. This person tried to open a PR against a project I'm the maintainer for as well (https://github.com/ixmatus/inflector/pull/16). Users can get statistics from `libraries.io` which is linked to directly by pypi itself.

**Pull request closed without merging**
