### PR TITLE
Remove shebangd from modules code (ESPTOOL-453)

### PR DESCRIPTION
**Pull request by kloczek**
Remove not needed shebangs from all modules code.

Signed-off-by: Tomasz Kłoczko <kloczek@github.com>

### CODE REVIEW

**Comment by radimkarnis** [comment]
Hi @kloczek,

thanks for contributing!

I agree some of the shebangd lines can be removed, but not all of them. For instance - the test scripts in the `test` folder are all meant to be executed with a Python interpreter.

If you don't mind going over the PR and removing only the unnecessary ones, we can accept this PR!

**Comment by kloczek** [comment]
None odf the test/ directory files are executed as scripts.
For exmple I have no `python` executable (only `python3`).
In other words even tose files can drop shebang (end exec atribute as well).

**Comment by jaryn** [comment]
You are removing all the shebang. Do all the tools still work under the linux systems that need to be supported? Are there some tests testing this? If there are none, should there be some?

Also I found this solution: https://www.google.com/search?client=firefox-b-e&q=python-is-python3 have this been considered?

Thanks

**Comment by kloczek** [comment]
Here is diffstat of that commit
```console
$ diffstat esptool-schebangs.patch
 esp_rfc2217_server.py                                   |    2 +-
 espefuse.py                                             |    2 +-
 espefuse/__init__.py                                    |    2 --
 espefuse/__main__.py                                    |    2 --
 espefuse/efuse/base_fields.py                           |    2 --
 espefuse/efuse/base_operations.py                       |    2 --
 espefuse/efuse/emulate_efuse_controller_base.py         |    2 --
 espefuse/efuse/esp32/emulate_efuse_controller.py        |    2 --
 espefuse/efuse/esp32/fields.py                          |    2 --
 espefuse/efuse/esp32/mem_definition.py                  |    2 --
 espefuse/efuse/esp32/operations.py                      |    2 --
 espefuse/efuse/esp32c2/emulate_efuse_controller.py      |    2 --
 espefuse/efuse/esp32c2/fields.py                        |    2 --
 espefuse/efuse/esp32c2/mem_definition.py                |    2 --
 espefuse/efuse/esp32c2/operations.py                    |    2 --
 espefuse/efuse/esp32c3/emulate_efuse_controller.py      |    2 --
 espefuse/efuse/esp32c3/fields.py                        |    2 --
 espefuse/efuse/esp32c3/mem_definition.py                |    2 --
 espefuse/efuse/esp32c3/operations.py                    |    2 --
 espefuse/efuse/esp32h2beta1/emulate_efuse_controller.py |    2 --
 espefuse/efuse/esp32h2beta1/fields.py                   |    2 --
 espefuse/efuse/esp32h2beta1/mem_definition.py           |    2 --
 espefuse/efuse/esp32h2beta1/operations.py               |    2 --
 espefuse/efuse/esp32s2/emulate_efuse_controller.py      |    2 --
 espefuse/efuse/esp32s2/fields.py                        |    2 --
 espefuse/efuse/esp32s2/mem_definition.py                |    2 --
 espefuse/efuse/esp32s2/operations.py                    |    2 --
 espefuse/efuse/esp32s3/emulate_efuse_controller.py      |    2 --
 espefuse/efuse/esp32s3/fields.py                        |    2 --
 espefuse/efuse/esp32s3/mem_definition.py                |    2 --
 espefuse/efuse/esp32s3/operations.py                    |    1 -
 espefuse/efuse/esp32s3beta2/emulate_efuse_controller.py |    2 --
 espefuse/efuse/esp32s3beta2/fields.py                   |    2 --
 espefuse/efuse/esp32s3beta2/mem_definition.py           |    2 --
 espefuse/efuse/esp32s3beta2/operations.py               |    1 -
 espefuse/efuse/mem_definition_base.py                   |    2 --
 espefuse/efuse/util.py                                  |    2 --
 espsecure.py                                            |    2 +-
 espsecure/__init__.py                                   |    2 --
 espsecure/__main__.py                                   |    2 --
 esptool.py                                              |    2 +-
 esptool/__init__.py                                     |    2 --
 esptool/__main__.py                                     |    2 --
 flasher_stub/compare_stubs.py                           |    2 --
 flasher_stub/esptool_test_stub.py                       |    2 --
 flasher_stub/wrap_stub.py                               |    2 --
 test/test_espefuse.py                                   |    2 --
 test/test_espefuse_host.py                              |    2 --
 test/test_espsecure.py                                  |    2 --
 test/test_esptool.py                                    |    1 -
 test/test_imagegen.py                                   |    1 -
 test/test_merge_bin.py                                  |    1 -
 test/test_modules.py                                    |    2 --
 53 files changed, 4 insertions(+), 97 deletions(-)
```
So effectively this PR removes only module and test suite shebangs (+few other files) and is not removing all other shebangs which are needed.

**Comment by radimkarnis** [comment]
Hello @kloczek,

I am very sorry for not getting back to you earlier. We can proceed with this PR now!

I need to ask you to do two things:
1) Keep the test suite shebangs (needed for our internal purposes)
2) Rebase on top of master

After that, I will put this through our internal review queue and merge, thanks a lot!

**Comment by kloczek** [comment]
> I need to ask you to do two things:
> 
> 1. Keep the test suite shebangs (needed for our internal purposes)

Every single test unit can be executed by `pytest <tests/file.py>:<test::unit>`
None of those shebangs are needed.

**Comment by radimkarnis** [comment]
> Every single test unit can be executed by pytest <tests/file.py>:<test::unit>

First of all, we are not using pytest in our internal CI. Secondly, I can't accept this PR if you don't keep the test suite shebangs.

**Comment by kloczek** [comment]
I would strongly reccomed start using pytest + few extensions like 'pytest-cov`, `pytest-black`, `pytest-randomly`.

**Comment by radimkarnis** [comment]
Yes, we still have a task open https://github.com/espressif/esptool/issues/747 since the last time you recommended us to use pytest. FYI, we are not strangers to pytest at all. We develop our own plugin [pytest-embedded](https://github.com/espressif/pytest-embedded), which is designed specifically for embedded testing.

**Comment by radimkarnis** [comment]
Closing this PR for now. It is unnecessary and can't be accepted in this state. I am leaving https://github.com/espressif/esptool/issues/747 open - when we choose to start using pytest in the esptool project, we can look into this more.

**Pull request closed without merging**
