### PR TITLE
Python2 and 3 process encodings

### PR DESCRIPTION
**Pull request by thespooler**
Interprets process outputs as UTF-8 strings since the symbols used in `get_symbol_addr()` are expected to be utf, as invoked in `elf2image()`.

### CODE REVIEW

**Comment by thespooler** [comment]
Tested under Gentoo with utf8 locale
```
# locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

**Comment by projectgus** [comment]
Thanks for this, @thespooler .

This PR seems to have been targeted at the python2_and_3 branch, however this branch is merged (as of a couple of weeks ago) - can you re-target to master please? I'll delete the branch (should have done so when support was merged.)

**Comment by projectgus** [comment]
Ah, deleting the python2_and_3 branch deleted this pull request. That makes sense I guess, sorry for the hassle though! Please reopen against master when you can.

**Comment by thespooler** [comment]
Done in #159.

**Pull request closed without merging**
