### PR TITLE
Components (ESPTOOL-165)

### PR DESCRIPTION
**Pull request by eykamp**
Builds on my previous PR.

# Description of change
Permit passing an already formed esp object to main(), and pull out some functionality into separate functions so it can be called independently from other scripts.  Extracting this functionality also makes the program easier to understand.

Should result in no change in functionality when used in current use cases.

### CODE REVIEW

**Comment by projectgus** [comment]
Refactoring in here LGTM, anything which takes a big block of code and moves it into a function is welcomed!

My only comment is the same one from #401, to try and keep it possible for `esptool.main()`  to be called as-is.

**Comment by radimkarnis** [comment]
Hello @eykamp,
I'm guessing you may have lost some interest over the past 20 months. Do you still want to go on with this PR, or is it okay if I close it? Thank you

Radim

**Comment by eykamp** [comment]
Well... this project is on hiatus for me, so I have lost a degree of interest.  However, it looks like resolving this conflict will be pretty easy, so I'm going to go for it.  You can close this if you haven't heard from me in a week or so.

**Comment by eykamp** [comment]
Regarding the comment from @projectgus, I don't know if it's still relevant.  If it is, I don't understand it, but it looks like the requested changes are minor so am happy to resolve it however is good.

**Pull request closed without merging**
