### PR TITLE
Update miniz to 2.1.0

### PR DESCRIPTION
**Pull request by paravoid**
Update miniz to the latest version, 2.1.0. This is the stock, amalgated
miniz, with a few modifications, forward-ported from the existing diff
against 1.5:
 * Configuration options (the definitions at the top of miniz.h)
 * Disabling assert(), i.e. defining MZ_ASSERT to nothing
 * Defining TDEFL_LESS_MEMORY to 1
 * Setting TDEFL_LZ_DICT_SIZE = 8*1024 and TDEFL_LZ_CODE_BUF_SIZE = 8 * 1024

An additional complication is that the new miniz performs a long long to
integer division, which requires code from libgcc (__ashldi3), which we
didn't link to by default (due to -nostdlib). Add -lgcc to LDLIBS.

This seems to be a small increase in .text (8018->8023) with the stock
toolchain, but with a newer one (gcc 9.2.1/picolibc 1.3) actually
results in a decrease (7990->7947).

Tested on real hardware (D1 Mini Pro).

See #499 for some additional context.

### CODE REVIEW

**Comment by projectgus** [comment]
Hi @paravoid ,

Thanks for this, I hadn't actually noticed that miniz development was continuing on GitHub.

I've cherry-picked your commit into our internal review & merge queue, this PR will be updated when it merges.

Angus

**Comment by paravoid** [comment]
Thanks!

On that note, a two-parter idea to ease future migrations to newer versions:
- It'd be useful to expose the changes changes to separate config options: expose TDEFL_LESS_MEMORY as MINIZ_LESS_MEMORY, and maybe the DICT_SIZE/CODE_BUF_SIZE as MINIZ_EVEN_LESS_MEMORY or something? I don't feel confident enough to support those dict size changes and such, so perhaps it would make sense for you or someone this project to raise that with miniz upstream?
- I filed richgel999/miniz#145 to ask for the config to be split into a different header file. Hopefully that could allow us to commit an esptool-specific miniz_config.h separately in this project, and then just carry a pristine miniz.h/c without code changes in this project.

**Comment by projectgus** [comment]
Cherry-picked as 18647f2, thanks @paravoid :)

**Comment by projectgus** [comment]
@paravoid Just saw your suggestions. Agree these sound good, making miniz into a submodule or something would be a nice cleanup. Will see what I can do.

**Pull request closed without merging**
