### PR TITLE
Fix typos (ESPTOOL-853)

### PR DESCRIPTION
**Pull request by BoryaGames**
Just fix typos in comment.

# I have tested this change with the following hardware & software combinations:
NO TESTING

# I have run the esptool.py automated integration tests with this change and the above hardware:
NO TESTING

### CODE REVIEW

**Comment by radimkarnis** [comment]
Hello @BoryaGames,
thanks for the contribution! We had a very similar PR quite recently, please see the discussion and my suggestions here: https://github.com/espressif/esptool/pull/974

To sum up:
1) please change the commit message according to the bot report 
```
the commit message "Two typos":
summary looks empty
type/action looks empty
```
2) please rebase on top of master

The we can merge it!

**Comment by BoryaGames** [comment]
Hello @radimkarnis, sorry, can you help me how to change commit message and rebase? I'm not really good with GitHub.

**Comment by radimkarnis** [comment]
I would suggest learning some basic workflows with the git versioning system (using a GUI client or on the command line). 

1) You can clone your repository [BoryaGames:master](https://github.com/BoryaGames/esptool/tree/master) and then run the `git commit --amend` command to change the commit message. The you push the changes with `git push --force`. [Instructions here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).

2) Rebasing on GitHub is easy, just go to your repo [BoryaGames:master](https://github.com/BoryaGames/esptool/tree/master) and look for the `This branch is 1 commit ahead of, 2 commits behind espressif/esptool:master.` message. Then click the `Sync fork` button next to it. [Instructions here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).

**Comment by BoryaGames** [comment]
Done, @radimkarnis, I did what you asked.

**Comment by radimkarnis** [comment]
Thank you @BoryaGames,
I am sorry, but the commit message is still not ok. We follow [conventional commits style](https://www.conventionalcommits.org/en/v1.0.0/) of commit messages. Everything is explained in the [bot report above](https://github.com/espressif/esptool/pull/977#issuecomment-2084807332). Please try to come up with a suitable commit message. I suggest something like `change(detect_chip): Fixed a spelling mistake`.

Also, now there are two commits for a single change. Can we get rid of the merge commit? Thank you.

**Comment by BoryaGames** [comment]
Done, @radimkarnis. I merged these commits and changed message.

**Comment by radimkarnis** [comment]
@BoryaGames thank you for the contribution! Your commit is now merged.

**Pull request closed without merging**
