### PR TITLE
Fix typo in serial protocol docs (ESPTOOL-667)

### PR DESCRIPTION
**Pull request by hasheddan**
# Description of change

Fixes misspelling of `triggered` in serial protocol docs.

### CODE REVIEW

**Comment by radimkarnis** [comment]
Hi @hasheddan,
thank you for fixing that.
There is no need to make the other rows of the table longer. Can you please just delete some spaces for the symbols you've added without changing the other rows?

**Review by hasheddan — COMMENTED** [review]
Sure thing @radimkarnis -- done!

**Comment by radimkarnis** [comment]
Hi @hasheddan,
thanks! 
image
Unfortunately, the lines in the table have to be the same length, you can see your edited line is now two symbols longer. Please delete two spaces and we are good to go!

**Review by hasheddan — COMMENTED** [review]
@radimkarnis thanks -- done!

**Comment by radimkarnis** [comment]
@hasheddan Thanks for contributing!

**Pull request merged**
