### PR TITLE
Flasher stub: Increase CPU frequency to 240 MHz for ESP32-S3 (ESPTOOL-521)

### PR DESCRIPTION
**Pull request by Emill**
# Description of change

Increase clock speeds for ESP32-S3.

This increases CPU frequency from 20 MHz to 240 MHz and SPI frequency from 5 MHz to 20 MHz.

This results in ~2x faster flashing performance in total.

The power consumption impact has not been studied.

# This change fixes the following bug(s):

(https://github.com/espressif/esptool/issues/779), but only for ESP32-S3. Someone who has access to other boards can probably submit a similar patch for such boards.

# I have tested this change with the following hardware & software combinations:

ESP32-S3-WROOM-1

# I have run the esptool.py automated integration tests with this change and the above hardware. The results were:

```
Running esptool.py tests...
...s....sss..........................s.....s.s...s.......s......
----------------------------------------------------------------------
Ran 64 tests in 526.718s

OK (skipped=9)
```

### CODE REVIEW

**Comment by igrr** [comment]
One note is that we should restore the original setting when exiting the stub (e.g. if `load_ram` is used). Otherwise the apps built before this feature is introduced will unexpectedly start running at a higher CPU and APB frequency.

**Comment by radimkarnis** [comment]
@Emill, 

could you please update the PR to first store the original settings before increasing CPU freq and to restore the original settings when exiting the stub? (commands in question: `ESP_FLASH_END`, `ESP_FLASH_DEFLATED_END`, `ESP_MEM_END`, `ESP_RUN_USER_CODE`)

If not, I can finish this feature, please let me know!

**Comment by Emill** [comment]
Do you think there is any issues regarding power consumption (peak power for example) of the increased cpu frequency?

**Comment by radimkarnis** [comment]
The only issue I can think of might be the chip becoming more prone to browning out if an insufficient power supply is used.

**Comment by Emill** [comment]
I was more thinking of people who try to flash a board that runs on a weak power supply, like a battery or something.

**Comment by radimkarnis** [comment]
@Emill yes, I believe we are mentioning the same thing. I think we can implement this and see if any serious issues with weaker power supplies arise.

**Comment by Emill** [comment]
I can revert the previous cpu setting whenever `stub_main` returns.

When `ESP_FLASH_END` etc. ends in a `software_reset()`, do I need to revert the settings there as well or will a reset automatically reset the cpu frequency?

For, `ESP_MEM_END`, should the cpu settings be reverted while `entrypoint_fn` is running?

**Comment by radimkarnis** [comment]
We need to restore the settings in all of these four cases, the CPU freq can be increased only while stub logic is running.

**Comment by radimkarnis** [comment]
Hi @Emill,
are you planning to work on this or should I pick this up? 😊 thank you and please let me know!

**Pull request closed without merging**
