### PR TITLE
In setup.py specify console_scripts rather than scripts (better cross…

### PR DESCRIPTION
**Pull request by hickford**
…-platform compability). See https://packaging.python.org/distributing/#scripts. Fixes https://github.com/espressif/esptool/issues/181

Tested on Windows

The principal benefit is that on Windows the application will be installed as `esptool.exe` rather than `esptool.py`

### CODE REVIEW

**Comment by projectgus** [comment]
Thanks for sending this. I wasn't actually aware this feature existed!

This seems like the right way to do things, but I have one major concern around backwards compatibility. Essentially every guide, howto, makefile, script, etc. that runs esptool.py runs it as `esptool.py` not `esptool`.  This PR will change that naming. Also, there's at least [one other active project](https://github.com/igrr/esptool-ck), and I think at least one older project, that called itself esptool. Up until now it was possible to have both installed simultaneously without a conflict.

V2.0 changes some other behaviour of esptool.py v1.x, but it hasn't made any major breaking changes of this kind. This would be the first.

A partial workaround may be to install as scripts and as console_scripts, so both forms (`esptool` and `esptool.py`) will work. Or to at least do that on Windows, where the downsides of naming the script `esptool.py` are more obvious.

This might be too out there, but installing `esptool.py.exe` and friends on Windows might also keep things fully backwards compatible... But seems a bit icky.

**Comment by projectgus** [comment]
Actually, the more I think about it specifying the console_scripts names as `esptool.py`, etc. might be the best compromise. Keen to know what you think.

**Comment by hickford** [comment]
I understand your concern about backwards compatibility.

Just tried out your suggestion `esptool.py=esptool:_main` that solves my problems on Windows. Let me update the pull request.

**Comment by hickford** [comment]
Updated pull request. How about that?

**Comment by projectgus** [comment]
Sorry for the long delay, got busy with other things and couldn't get back to esptool. This looks great, cheers.

**Pull request merged**
