### PR TITLE
Fixed Spelling Mistake (ESPTOOL-850)

### PR DESCRIPTION
**Pull request by GreenDiscord**
I fixed a spelling mistake in the docs, it spelled something instead of devices.

# This change fixes the following bug(s):
 

# I have tested this change with the following hardware & software combinations:
 NO TESTING

# I have run the esptool.py automated integration tests with this change and the above hardware:
 NO TESTING

### CODE REVIEW

**Comment by radimkarnis** [comment]
Hello @GreenDiscord,
thank you for the contribution and for noticing the spelling mistake!

We'll merge it soon, I just need you to change the commit message (please see the previous message from our bot).

I suggest something like `docs(flashing): Fixed a typo`.

Thank you!

**Comment by GreenDiscord** [comment]
@radimkarnis there ya go :D 
First time changing a commit message properly, sorry for taking a sec.

**Comment by radimkarnis** [comment]
Thanks! All looks good now. I will put this through our internal queue and merge it.

**Comment by radimkarnis** [comment]
Hey @GreenDiscord,
sorry to give you a headache over a simple PR.

Turns out your commit is not on top of the current master branch. Could you please rebase? I could do that for you, but then you would loose the github credit for the contribution (since I would alter your commit).

Also, my suggestion of the `docs(flashing): Fixed a typo` commit message is not correct. Turns out, the commit message checker still doesn't like it (see the `summary looks too short` message above). Sorry about that 😊 if you'll be rebasing this, you can also deal with this by extending the commit message. But that's not a deal breaker, just a suggestion from our system.

**Pull request closed without merging**
