### PR TITLE
PEP8 imports  Remove unused import statements.

### PR DESCRIPTION
**Pull request by Cabalist**
This shouldn't change any functionality.  This is just sorting imports and cleaning up the unused top-level imports.

It follows these guidelines:
https://www.python.org/dev/peps/pep-0008/#imports

### CODE REVIEW

**Comment by projectgus** [comment]
Thanks for thinking of this cleanup. I appreciate all these PRs!

The ecdsa & pyaes subdirectories are "vendored" libraries that are copied from their upstream versions. So I'd rather not make any changes there, so that it's easy to pull upstream changes without needing to resolve conflicts. Feel free to submit these cleanups direct to the upstreams, though.

If you amend the PR to take out the take out the vendored libraries, I'd be more than happy to merge.

**Comment by projectgus** [comment]
One other addition, if you feel like it, would be to add flake8-import-order to the Flake8 dependencies so Travis can check future import additions remain in order.

**Comment by Cabalist** [comment]
I didn't realize they were upstream.  Oops!  

The changes to upstream have been reverted and the flake8-import-order has been added.  :)

**Comment by projectgus** [comment]
Thanks, looks great! Sorry for the slow turnaround on this.

**Comment by Cabalist** [comment]
No worries.  Thanks for accepting.  :)

**Pull request merged**
